### ISSUE TITLE
Java-8-jdk

### ISSUE THREAD

**Issue by SamSanuch** [xeffyr/termux-rootfs-addons#2]
Watch this and How can I contact you sir? I have build java-8-jdk as shown in video but I can't add there(in your rootfs)
May you add my work there? https://asciinema.org/a/z6Egel7sqTZUdCHqDVcROuYLB
https://mega.nz/#!0jJRXRJQ!F5XBEPYsP9T5HuKpZWiwQc6Yjshs0BNKsyW9-E1k9YI

**Comment by xeffyr** [comment]
I will add Java 8 to [termux-rootfs](https://github.com/xeffyr/termux-rootfs) because this is essential package and it will replace OpenJDK-7 (which was JRE only).

**Comment by SamSanuch** [comment]
@xeffyr 
Thanks sir!

**Comment by xeffyr** [comment]
Now Java 8 (JDK) added in Termux Rootfs and will be available in version 4.9.
Closed.
